language: python
python:
  - 3.6

services:
  - docker

install:
  - docker build -t max-named-entity-tagger .
  - docker run -it -d -p 5000:5000 max-named-entity-tagger

before_script:
  - pip install pytest requests
  - sleep 30

script:
  - pytest tests/test.py
